name: Fetch Movie Titles

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC

jobs:
  fetch-titles:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Updated to Node 18 for better compatibility

      - name: Install dependencies
        run: npm install

      - name: Create .env file
        run: |
          echo "MUST_USERNAME=subhransu" >> .env
          echo "FETCH_WATCHED=true" >> .env
          echo "FETCH_WANTS=true" >> .env
          echo "FETCH_SHOWS=true" >> .env
          echo "GENERATE_STATS=true" >> .env
          echo "GENERATE_HTML_REPORT=false" >> .env
          echo "CREATE_BACKUP=false" >> .env

      - name: Fetch Titles and Generate Reports
        run: node movies.js

      - name: Sync to Supabase Database
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          MUST_USERNAME: subhransu
        run: node utils/sync-to-supabase.js

      - name: Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🎬 Updated movie titles and stats (synced to database)"
          file_pattern: "*.csv STATS.md"
